version: '3'
services: 
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports: 
      - "3000:3000"
    volumes: 
      - /usr/app/node_modules
      - .:/usr/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /usr/app/node_modules
      - .:/usr/app
    command: ["npm","run","test"]
